// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Enum is an autogenerated mock type for the Enum type
type Enum struct {
	mock.Mock
}

// IsValid provides a mock function with given fields:
func (_m *Enum) IsValid() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewEnum interface {
	mock.TestingT
	Cleanup(func())
}

// NewEnum creates a new instance of Enum. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEnum(t mockConstructorTestingTNewEnum) *Enum {
	mock := &Enum{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
