// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	io "io"
	http "service-shared/http"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Get provides a mock function with given fields: url
func (_m *Client) Get(url string) (*http.ClientResponse, error) {
	ret := _m.Called(url)

	var r0 *http.ClientResponse
	if rf, ok := ret.Get(0).(func(string) *http.ClientResponse); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.ClientResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Post provides a mock function with given fields: url, contentType, body
func (_m *Client) Post(url string, contentType string, body io.Reader) (*http.ClientResponse, error) {
	ret := _m.Called(url, contentType, body)

	var r0 *http.ClientResponse
	if rf, ok := ret.Get(0).(func(string, string, io.Reader) *http.ClientResponse); ok {
		r0 = rf(url, contentType, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.ClientResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, io.Reader) error); ok {
		r1 = rf(url, contentType, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
