// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PublishQueue is an autogenerated mock type for the PublishQueue type
type PublishQueue struct {
	mock.Mock
}

// PublishPollRequest provides a mock function with given fields: bankApplicationID, ourApplicationID
func (_m *PublishQueue) PublishPollRequest(bankApplicationID string, ourApplicationID string) error {
	ret := _m.Called(bankApplicationID, ourApplicationID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(bankApplicationID, ourApplicationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPublishQueue interface {
	mock.TestingT
	Cleanup(func())
}

// NewPublishQueue creates a new instance of PublishQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPublishQueue(t mockConstructorTestingTNewPublishQueue) *PublishQueue {
	mock := &PublishQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
